[build]
  base = "/"
  command = "npm run build"
  publish = "/.next"
  functions = "/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[secrets]
  omit_keys = ["NEXT_PUBLIC_SUPABASE_ANON_KEY", "NEXT_PUBLIC_SUPABASE_URL"]
